name: quantum_sync
description: The ultimate logic puzzle game with 100 brutally challenging levels
publish_to: 'none'
version: 2.2.0+2

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.2.2
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.2
  vibration: ^1.8.4
  google_mobile_ads: ^5.0.0
  in_app_update: ^4.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  change_app_package_name: ^1.5.0

flutter:
  uses-material-design: true

  # App icon configuration
  assets:
    - assets/images/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700

# App icon configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon_foreground.png"
  adaptive_icon_background: "assets/images/icon_background.png"
  adaptive_icon_foreground: "assets/images/app_icon.png"
  #min_sdk_android: 21
  remove_alpha_ios: true